-- This schema is PostgreSQL-specific and populates 1001 items.

CREATE TABLE IF NOT EXISTS item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000)
);

-- Insert the default item so integration tests can rely on ID 1
INSERT INTO item (id, name, description)
VALUES (1, 'Default Item', 'An item pre-populated from data.sql')
ON CONFLICT (id) DO UPDATE SET name = 'Default Item', description = 'An item pre-populated from data.sql';

-- Set sequence to start after 1
ALTER SEQUENCE item_id_seq RESTART WITH 2;

-- Use a DO block to generate 1000 random items
DO $$
BEGIN
    FOR i IN 1..1000 LOOP
        INSERT INTO item (name, description)
        VALUES (
            'Item ' || i,
            'Random description ' || md5(random()::text)
        );
    END LOOP;
END $$;
